// Generated by scripts/sync-release-notes.mjs. Do not edit manually.
import type { ReleaseNotesContent } from "./types"

export const currentReleaseNotes = {
  version: "1.0.60",
  date: "2026-06-10",
  notes: {
    en: '### ✨ Improvements\n\n- **Userscript bundle size** — Split Markdown rendering code, Markdown styles, user-query Markdown styles, and site icons into external userscript assets so Greasy Fork sync has less inline code to process while preserving the existing rendering injection path.\n- **Zen Mode exit button** — Added a "Show exit button" setting for Zen Mode, so the on-page exit button can be hidden while keeping the quick button and shortcut exit paths available. (#645)\n\n### 🐛 Bug Fixes\n\n- **AI Studio mobile Enter key** — AI Studio on Android and other mobile devices now lets the soft-keyboard Enter key insert a newline instead of triggering an accidental send, while Ophel-driven sends still use the native send button or the safe keyboard fallback. (#646)\n- **AI Studio mobile history sync** — AI Studio conversation sync now recognizes the mobile Library card layout, so mobile pages no longer report that no sidebar conversations were found when history is available.\n- **Conversation sync loading** — Conversation sync now uses each adapter\'s own conversation source to decide when sidebar history has finished loading, waits longer for slow lazy-loaded sidebars, and disables sync-delete when a complete load cannot be confirmed. Doubao and Yuanbao now share the safer base loader. (#639)',
    zh: "### ✨ 功能优化\n\n- **油猴脚本包体积** — 将 Markdown 渲染代码、Markdown 样式、用户提问 Markdown 样式和站点图标拆分为外部油猴资源，减少 Greasy Fork 同步时需要处理的内联代码，同时保持原有渲染注入路径不变。\n- **禅模式退出按钮** — 禅模式设置新增“显示退出按钮”开关，可隐藏页面上的退出按钮，保留快捷按钮和快捷键退出入口，避免遮挡标题或对话内容。(#645)\n\n### 🐛 问题修复\n\n- **AI Studio 移动端 Enter 键** — Android 等移动设备上的 AI Studio 现在会让软键盘 Enter 插入换行，不再误触发送；通过 Ophel 触发的发送仍会使用原生发送按钮或安全的键盘兜底。(#646)\n- **AI Studio 移动端历史同步** — AI Studio 会话同步现在可以识别移动端 Library 卡片布局，移动端有历史记录时不再误提示找不到侧边栏会话。\n- **会话同步加载** — 会话同步现在会使用各站点适配器自己的会话来源判断侧边栏历史是否加载完成，为慢速懒加载侧边栏等待更久，并在无法确认已完整加载时禁用同步删除；豆包和元宝也改为复用更安全的基类加载逻辑。(#639)",
  },
  fullChangelogUrls: {
    en: "https://ophel.app/docs/changelog",
    zh: "https://ophel.app/docs/zh/changelog",
  },
  media: [],
} as const satisfies ReleaseNotesContent
